Repository levina-lab/video-stream, pull requests merged in 2022-02, with the labels that each got.

#140 new updates v0.6.5
  README.md
  app.json
  config.py
  driver/core.py
  driver/database/dblockchat.py
  driver/database/dbqueue.py
  driver/database/dbusers.py
  driver/decorators.py
  driver/design/thumbnail.py
  driver/source/LightGreen.png
  driver/utils.py
  example.env
  main.py
  program/__init__.py
  program/admins.py
  program/blockchat.py
  program/callback.py
  program/developer.py
  program/downloader.py
  program/extra.py
  program/music.py
  program/playlist.py
  program/punishment.py
  program/speedtest.py
  program/start.py
  program/updater.py
  program/userbot_tools.py
  program/utils/inline.py
  program/video.py
  program/ytsearch.py
  requirements.txt
Labels: documentation, enhancement

#141 [fix] InviteHashExpired
  program/music.py
  program/userbot_tools.py
  program/video.py
Labels: good first issue

#144 [feat] Show tg audio's thumbnail
  driver/design/thumbnail.py
  program/music.py
Labels: enhancement

#146 [refactor] Use a decorator to handle blacklist
  driver/core.py
  driver/decorators.py
  program/admins.py
  program/callback.py
  program/downloader.py
  program/music.py
  program/playlist.py
  program/start.py
  program/userbot_tools.py
  program/video.py
  program/ytsearch.py
Labels: enhancement

#149 [feat] Support play tg url.
  driver/core.py
  driver/utils.py
  program/admins.py
  program/callback.py
  program/music.py
  program/playlist.py
  program/punishment.py
  program/start.py
  program/userbot_tools.py
  program/video.py
Labels: enhancement

#152 change format
  program/downloader.py
Labels: enhancement

#159 improvements
  driver/utils.py
  program/callback.py
  program/music.py
  program/userbot_tools.py
  program/video.py
Labels: enhancement

#167 {check] cleaning files
  config.py
  driver/utils.py
  program/admins.py
  program/blockchat.py
  program/developer.py
  program/downloader.py
  program/speedtest.py
  program/updater.py
  program/utils/inline.py
  program/ytsearch.py
Labels: enhancement

#169 [feat] some changes & improvements
  driver/core.py
  program/admins.py
  program/assistant_settings.py
  program/blockchat.py
  program/callback.py
  program/developer.py
  program/downloader.py
  program/essentials.py
  program/inline.py
  program/music_stream.py
  program/playlist.py
  program/punishment.py
  program/speedtest.py
  program/start.py
  program/sysinfo.py
  program/video_stream.py
  program/ytsearch.py
Labels: enhancement

#171 [new] some fixes and improvements
  main.py
  program/__init__.py
  program/callback.py
  program/sysinfo.py
Labels: enhancement
